version: '3'
volumes:
  data:
services:
  db:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - data:/var/lib/postgres
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq